Autenticacion usuario
unahur-covid/backend pull request #13
Opened 2021-01-19 23:54 UTC by CabreraTiago

Closes unahur-covid/planificacion#24

2021-01-20 00:50 UTC, faloi requested changes
Hay varios cambios para hacer, pero muy bien encarada una issue tan heavy. ¡Vamos! 💪🏽

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +        }
Tanto esta como las demás validaciones deberían ir al modelo. Ver https://sequelize.org/master/manual/validations-and-constraints.html.

2021-01-20 00:50 UTC, faloi commented on lib/models/usuario.js
> +        rol: DataTypes.STRING,
Acá deberían ir las validaciones y las constraints que pusieron en la migración, fijensé el link que les pasé más arriba.

2021-01-20 00:50 UTC, faloi commented on lib/models/usuario.js
> +};
Esto puede ir como un método de la clase, es un poco la gracia de tener clases. 😛

2021-01-20 00:50 UTC, faloi commented on lib/models/usuario.js
> +              bcrypt.genSaltSync()
Pregunto de ignorante: ¿el salt este no hay que guardarlo?

2021-01-20 00:50 UTC, faloi commented on lib/routes/usuarios.js
> +require('../middlewares/auth');
¿Para qué sirve requerir este módulo acá?

2021-01-20 00:50 UTC, faloi commented on lib/routes/usuarios.js
> +router.get('/', withErrorHandling(index));
Este index público es terrible agujero de seguridad. Tiene que ser con autenticación (y en el futuro solo para admin).

2021-01-20 00:50 UTC, faloi commented on package.json
> +    "body-parser": "^1.19.0",
Ya estaba como dependencia indirecta... ¿algún package necesitaba que esté acá de forma explícita?

2021-01-20 00:50 UTC, faloi commented on lib/controllers/usuario_controller.js
> +      return res.status(400).json({ error: err });
Un mal login debería devolver 401, no 400.

2021-01-20 00:50 UTC, faloi commented on lib/controllers/usuario_controller.js
> +  passport.authenticate('login', (err, data) => {
¿No hay una variante que devuelva promise? Es medio fulero andar mezclando callbacks con promises.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +    async (req, dni, contrasenia, done) => {
Acá también estaría bueno ver si no acepta una variante con promises... el `done` ese me hace un poco de ruido.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +  secretOrKey: process.env.SECRET_JWT_SEED,
Yo sé que en otras partes está así, pero no está muy bueno andar metiendo `process.env` por todos lados. Sugiero lo siguiente:

* crear un archivo dentro de `lib/config` que tenga las configuraciones que vienen del entorno (podría llamarse `env.js` o `auth.js` si solo va a tener las de auth,
* ponerle un valor default, para que en desarrollo (y en Travis, que ahora falla) no haga falta tener que configurarla. 

Este archivo en cuestión podría ser algo así: 

```js
export const jwtSecretSeed = process.env.SECRET_JWT_SEED || 'eStoNoEsSecReTo';
```

2021-01-20 00:50 UTC, faloi commented on lib/helpers/jwt.js
> +  return jwt.sign(payload, process.env.SECRET_JWT_SEED, { expiresIn: '180d' });
Y acá reutilizarían el archivo que les puse antes, así no se repite el nombre de la variable de entorno por todos lados.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +        }
Esta validación me parece innecesaria, podría pasar que dos personas compartan teléfono.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +        }
Además de que conceptualmente no es acá donde deberían estar, es poco óptimo el código: para crear un usuario hace 4 queries a la DB. Si se resuelve con una constraint unique va a hacer una sola, que eventualmente puede fallar.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +            'El DNI y/o contraseña ingresada son invalidas por favor vuelta a intentar.',
```suggestion
            'El DNI y/o contraseña ingresados son inválidos, por favor vuelva a intentar.',
```

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +            'El DNI y/o contraseña ingresada son invalidas por favor vuelta a intentar.',
Estaría bueno también meterlo en una `const` o algo, para no repetir abajo.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +        return done(null, { token: token });
Pavada: si la key se llama igual que la `const` no hace falta poner el nombre.

```suggestion
        return done(null, { token });
```

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +);
No me queda claro para qué sirve este.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +  secretOrKey: process.env.SECRET_JWT_SEED,
Para otra issue: si efectivamente la variable hay que definirla sí o sí, es buena práctica agregar un ejemplo a `.env.example` para que lxs demás sepan qué hay que poner ahí. Fijensé cómo están las credenciales de SQL.

2021-01-20 00:50 UTC, faloi commented on lib/middlewares/auth.js
> +  secretOrKey: process.env.SECRET_JWT_SEED,
Y la última (ya de denso): renombren a `JWT_SECRET_SEED`, así nos queda como "prefijo" el componente que necesita la variable.

2021-01-20 00:50 UTC, faloi commented on lib/controllers/edificio_controller.test.js
> +          .set('Authorization', `Bearer ${token}`);
Voy a investigar alguna manera de no tener que poner esto en cada test. Quise correrlos y me fallan todos, primero deberían resolver eso para que pueda hacer algunas pruebas.

2021-01-20 00:50 UTC, faloi commented on .vscode/launch.json
> +}
Si sirve lo dejamos, no me jode para nada, entiendo que lo usaron para debuguear una vez ejecutado el proceso. 

Por las dudas les cuento:
* Los tests se pueden debuguear directamente desde el Test Explorer, sin configurar nada.
* No me acuerdo cómo, pero el VScode tiene la capacidad de engancharse de un proceso Node corriendo si lo disparan desde la debug console.

Me anoto el tema para hacer un videito.

2021-01-20 00:50 UTC, faloi commented on lib/controllers/actividad_controller.test.js
> +    };
Una pequeña mejora: llevar este usuario de mentiritas a un archivo aparte, para no repetirlo en cada test. Incluso creo que podrían mover hasta el login inclusive y que la función ya devuelva el token.

2021-01-20 22:53 UTC, faloi commented on lib/models/usuario.js
> +};
```suggestion
  validarContrasenia(contraseniaAValidar) {
    return bcrypt.compareSync(contraseniaAValidar, this.contrasenia);
  }
}
```

2021-01-21 03:05 UTC, GerezPablo commented on lib/models/usuario.js
> +              bcrypt.genSaltSync()
Funciona igual ¿Cuál sería la diferencia entre guardarlo o no?

2021-01-21 03:09 UTC, GerezPablo commented on lib/routes/usuarios.js
> +require('../middlewares/auth');
`Error: Unknown authentication strategy`
Pasa que si no lo ponemos, no nos reconoce las estrategias y rompe, de cualquier forma, cambiamos el `require` por un `import`.

2021-01-21 03:15 UTC, CabreraTiago commented on package.json
> +    "body-parser": "^1.19.0",
Ok, no sabíamos eso. El `bcryptjs` también está marcado, ¿lo sacamos?

2021-01-21 09:45 UTC, faloi commented on lib/models/usuario.js
> +              bcrypt.genSaltSync()
Es que hay algo que no me cierra. El salt es un texto random que se agrega a la hora de encriptar, entonces la función de hash recibe `contrasenia + salt`. Cuando el usuario se loguea pone la contraseña pero no el salt... ¿cómo hacés para que el hash te de lo mismo?

2021-01-21 09:47 UTC, faloi commented on lib/routes/usuarios.js
> +require('../middlewares/auth');
Ok, aunque no me termina de convencer. Pero dejémoslo por ahora.

2021-01-21 09:48 UTC, faloi commented on package.json
> +    "body-parser": "^1.19.0",
Nono, si sacan el bcrypt se rompe todo.

2021-01-22 20:26 UTC, faloi requested changes

2021-01-22 20:26 UTC, faloi commented on db/migrations/20210115171617-create-usuario.js
> +        type: Sequelize.STRING,
Perdón, esta se me pasó en la review anterior, pero debería ser un ENUM tanto acá como en el modelo:

```suggestion
        type: Sequelize.ENUM('invitado', 'estudiante', ...)
```

2021-01-22 20:26 UTC, faloi commented on lib/config/auth.js
> +export const jwtSecretSeed = process.env.JWT_SECRET_SEED || 'eStoNoEsSecReTo';
¡Genial!

2021-01-22 20:26 UTC, faloi commented on lib/controllers/usuario_controller.js
> +      return res.status(400).json({ error: err.errors[0].message });
Fue, lo mergeamos así, ¿pero qué pasa si hubo varios errores?

Tal vez podríamos devolverlos todos:
```suggestion
      return res.status(400).json({ error: err.errors.map(it => it.message) });
```

2021-01-22 22:08 UTC, faloi approved these changes

2021-01-22 22:09 UTC, merged