Listar borrar espacios
unahur-covid/backend pull request #7
Opened 2020-12-31 02:49 UTC by GerezPablo

Closes #1

2020-12-31 10:58 UTC, faloi requested changes

2020-12-31 10:58 UTC, faloi commented on lib/controllers/espacio_controller.js
> +    attributes: ['id', 'piso', 'nombre', 'habilitado', 'aforo'],
¿Por qué especificar los atributos a mano si queremos que devuelva todos?

2020-12-31 10:58 UTC, faloi commented on lib/controllers/espacio_controller.js
> +    .catch((error) => res.status(500).send(error));
Este catch no hace falta, lo agarra el `withErrorHandling`.

2020-12-31 10:58 UTC, faloi commented on lib/controllers/espacio_controller.js
> +    .then((count) => {
Sería mejor manejarlo con `async/await`.

2020-12-31 10:58 UTC, faloi commented on lib/models/edificio.js
> +    this.myAssociation = this.hasMany(models.Espacio, {
¿Para qué sirve guardarse la asociación?

2020-12-31 10:58 UTC, faloi commented on lib/models/edificio.js
> +    });
No le veo sentido a ponerle un nombre, mejor usar el que pone Sequelize por defecto (`edificioId`).

2020-12-31 10:58 UTC, faloi commented on lib/models/espacio.js
> +  static associate(models) {
Mismos comentarios que en el otro `associate`.

2020-12-31 10:58 UTC, faloi commented on lib/models/espacio.js
> +      as: 'edificio',
No usaría el `as` a menos que sea realmente necesario, porque usarlo te obliga a ponerlo en todas las queries. Entiendo que en este caso se puede omitir.

2020-12-31 10:58 UTC, faloi commented on db/migrations/20201211172124-create-usuario.js
> +
Esta migra y el modelo `Usuario` también se podrían borrar. Lo mismo con el controller.

2020-12-31 10:58 UTC, faloi commented on db/migrations/20201229214856-create-edificio.js
> +        type: Sequelize.STRING,
No debería ser nullable este campo.

2020-12-31 10:58 UTC, faloi commented on db/migrations/20201229214900-create-espacio.js
> +        type: Sequelize.BOOLEAN,
¿Valor por defecto?

2020-12-31 10:58 UTC, faloi commented on db/migrations/20201229214900-create-espacio.js
> +  up: async (queryInterface, Sequelize) => {
Revisar campos nullables.

2020-12-31 10:58 UTC, faloi commented on lib/controllers/espacio_controller.js
> +          .send(`No existe un espacio con el id ${req.params.id}`);
Estaría mejor que sea un JSON. Por ejemplo: `{ "error": "..." }`.

2020-12-31 10:58 UTC, faloi commented on lib/controllers/espacio_controller.js
> +          .send(`No existe un espacio con el id ${req.params.id}`);
Y ya que estamos, no vendría mal un test de esta ruta. 😉

2020-12-31 11:44 UTC, faloi commented
Y una cosa más que me quedé pensando: si va a haber una entidad `Edificio` habría que meterle un CRUD, al menos para poder agregarlos nosotrxs vía API. En el frontend no haría una pantalla para esto.

2020-12-31 11:51 UTC, faloi commented on db/seeders/20201229221952-espacios.js
> +        edificioFk: 3,
No hace falta que lo cambien, solo como comentario futuro: es medio raro que esto dependa de un id de un elemento que se crea en otro seeder. Sería mejor crear los edificios acá mismo, y ver la forma de utilizar los id que efectivamente tengan (podrían no ser 1, 2 y 3).

2021-01-02 18:33 UTC, CabreraTiago commented on lib/models/edificio.js
> +    });
Intentamos sacarle el nombre pero solo funciona con `EdificioId`, con una mayúscula al comienzo. ¿Está bien así?

2021-01-02 18:45 UTC, GerezPablo commented on lib/models/edificio.js
> +    this.myAssociation = this.hasMany(models.Espacio, {
🤔 Pasa que si no las guardamos, cuando hacemos una petición se rompe.

``` console
SequelizeEagerLoadingError: Edificio is not associated to Espacio!
    at Function._getIncludedAssociation (/home/tiago/unahur-covid/backend/node_modules/sequelize/lib/model.js:717:13)
    at Function._validateIncludedElement (/home/tiago/unahur-covid/backend/node_modules/sequelize/lib/model.js:621:53)
    at /home/tiago/unahur-covid/backend/node_modules/sequelize/lib/model.js:516:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/home/tiago/unahur-covid/backend/node_modules/sequelize/lib/model.js:511:39)
    at /home/tiago/unahur-covid/backend/node_modules/sequelize/lib/model.js:1728:14
    at processImmediate (internal/timers.js:461:21)
```

2021-01-02 20:30 UTC, faloi commented on lib/models/edificio.js
> +    this.myAssociation = this.hasMany(models.Espacio, {
No es que no te crea, pero me resulta muy raro... Dejenlo y después lo pruebo.

2021-01-02 20:32 UTC, faloi commented on lib/models/edificio.js
> +    });
Mmmm, el problema es entonces que pusimos el `modelName` con la primera letra mayúscula. Cambien eso en todas las entidades y el nombre de la FK va a quedar bien.

2021-01-02 20:35 UTC, faloi commented on lib/controllers/espacio_controller.js
> +  !espacio
Es confuso usar el operador ternario si no se devuelve una expresión. Mejor usar `if`.

2021-01-02 20:37 UTC, merged

2021-01-02 20:43 UTC, faloi commented
Les mergeo el PR para que avancen con la siguiente issue. Resuelvan ahí las cosas que quedaron pendientes (y agreguen tests así Travis deja de fallar porque no hay ninguno 🤪).